import type { Metadata } from "next";
import { LegalLayout } from "@/components/legal/LegalLayout";
import { LegalSection } from "@/components/legal/LegalSection";
import { LegalNotice } from "@/components/legal/LegalNotice";

export const metadata: Metadata = {
  title: "Terms of Service | Fyzer Healthcare Platform",
  description: "The terms that govern use of the Fyzer healthcare platform.",
};

const toc = [
  { id: "acceptance", label: "Acceptance of Terms" },
  { id: "eligibility", label: "Eligibility and Authorized Use" },
  { id: "accounts", label: "User Accounts and Account Security" },
  { id: "services", label: "Healthcare Platform Services" },
  { id: "patient-data", label: "Patient Data Access" },
  { id: "ai-assistant", label: "AI Assistant" },
  { id: "medical-disclaimer", label: "Medical Disclaimer" },
  { id: "emergency", label: "Emergency Situations" },
  { id: "user-responsibilities", label: "User Responsibilities" },
  { id: "prohibited", label: "Prohibited Activities" },
  { id: "professionals", label: "Healthcare Professional Responsibilities" },
  { id: "third-party", label: "Third-Party Services" },
  { id: "intellectual-property", label: "Intellectual Property" },
  { id: "availability", label: "Service Availability" },
  { id: "liability", label: "Limitation of Liability" },
  { id: "termination", label: "Suspension and Termination" },
  { id: "changes", label: "Changes to the Terms" },
  { id: "applicable-law", label: "Applicable Law" },
  { id: "contact", label: "Contact" },
];

export default function TermsOfServicePage() {
  return (
    <LegalLayout
      title="Terms of Service"
      subtitle="Fyzer Healthcare Platform"
      lastUpdated="5 October 2026"
      toc={toc}
    >
      <LegalSection id="acceptance" number={1} heading="Acceptance of Terms">
        <p>
          By accessing or using the Fyzer healthcare platform, you agree to these Terms of Service.
          If you do not agree, you should not use the platform.
        </p>
      </LegalSection>

      <LegalSection id="eligibility" number={2} heading="Eligibility and Authorized Use">
        <p>
          You may use Fyzer only if you are legally permitted to do so and only for purposes you are
          authorized to carry out. Where the platform is used on behalf of a minor or another
          person, you must be a parent, guardian or legally permitted representative where required.
        </p>
      </LegalSection>

      <LegalSection id="accounts" number={3} heading="User Accounts and Account Security">
        <p>
          Users are responsible for maintaining the confidentiality of their login credentials and
          must report suspected unauthorized account access to{" "}
          <a href="mailto:admin@fyzer.com">admin@fyzer.com</a>.
        </p>
      </LegalSection>

      <LegalSection id="services" number={4} heading="Healthcare Platform Services">
        <p>
          Fyzer is a technology platform designed to support healthcare workflows, which may
          include patient accounts, appointment management, access to authorized medical
          information, healthcare communication and AI-assisted features.
        </p>
      </LegalSection>

      <LegalSection id="patient-data" number={5} heading="Patient Data Access">
        <ul>
          <li>
            Users must not attempt to access another patient&apos;s information unless proper
            authorization exists.
          </li>
          <li>
            Clinical users must only access records necessary for their authorized responsibilities.
          </li>
          <li>
            Attempts to circumvent authentication, authorization or access controls are prohibited.
          </li>
        </ul>
      </LegalSection>

      <LegalSection id="ai-assistant" number={6} heading="AI Assistant">
        <p>
          AI-assisted features are provided to help users understand information and navigate the
          platform. AI-generated content may contain errors and must be reviewed where clinical
          decision-making is involved. It must not automatically be considered a medical diagnosis,
          prescription or treatment.
        </p>
      </LegalSection>

      <LegalSection id="medical-disclaimer" number={7} heading="Medical Disclaimer">
        <LegalNotice variant="info" title="Medical Disclaimer">
          <p>
            Fyzer is a technology platform designed to support healthcare workflows. Information
            presented through the platform or generated by AI-assisted features must not
            automatically be considered medical diagnosis, prescription or treatment.
          </p>
          <p className="mt-2">
            Clinical decisions must remain under appropriately qualified healthcare professionals.
          </p>
          <p className="mt-2">
            AI-generated content may contain errors and must be reviewed where clinical
            decision-making is involved.
          </p>
        </LegalNotice>
      </LegalSection>

      <LegalSection id="emergency" number={8} heading="Emergency Situations">
        <LegalNotice variant="warning" title="Emergency Disclaimer">
          <p>Fyzer and its AI features are not emergency medical services.</p>
          <p className="mt-2">
            Users experiencing a medical emergency should immediately contact the appropriate local
            emergency service or visit the nearest emergency department.
          </p>
        </LegalNotice>
      </LegalSection>

      <LegalSection id="user-responsibilities" number={9} heading="User Responsibilities">
        <ul>
          <li>Provide information that is accurate and kept up to date.</li>
          <li>Keep login credentials confidential and report suspected unauthorized access.</li>
          <li>Use the platform only for authorized and lawful purposes.</li>
          <li>Access only the information you are authorized to access.</li>
        </ul>
      </LegalSection>

      <LegalSection id="prohibited" number={10} heading="Prohibited Activities">
        <p>You must not engage in any of the following:</p>
        <ul>
          <li>Unauthorized patient-record access</li>
          <li>Attempting to bypass authorization</li>
          <li>Impersonating another user</li>
          <li>Uploading malicious software</li>
          <li>Scraping protected medical information</li>
          <li>Manipulating clinical information without authorization</li>
          <li>Attempting to interfere with platform security</li>
          <li>Using another person&apos;s credentials without authorization</li>
          <li>Using AI features to intentionally generate harmful or fraudulent healthcare information</li>
        </ul>
      </LegalSection>

      <LegalSection id="professionals" number={11} heading="Healthcare Professional Responsibilities">
        <p>
          Healthcare professionals using Fyzer remain responsible for their own clinical judgment
          and professional obligations. They must only access records necessary for their
          authorized responsibilities and must review AI-generated content before relying on it in
          clinical decision-making.
        </p>
      </LegalSection>

      <LegalSection id="third-party" number={12} heading="Third-Party Services">
        <p>
          The platform may integrate with external healthcare, infrastructure or technical
          services. Those services are governed by their own terms and privacy practices.
        </p>
      </LegalSection>

      <LegalSection id="intellectual-property" number={13} heading="Intellectual Property">
        <p>
          The Fyzer platform, including its software, design and content, is protected by
          intellectual property rights. You may not copy, modify, distribute or reverse engineer
          any part of the platform except as permitted by law or in writing.
        </p>
      </LegalSection>

      <LegalSection id="availability" number={14} heading="Service Availability">
        <p>
          Fyzer aims to keep the platform available but does not guarantee uninterrupted or
          error-free operation. The platform may be unavailable from time to time, for example
          during maintenance or because of events outside Fyzer&apos;s control.
        </p>
      </LegalSection>

      <LegalSection id="liability" number={15} heading="Limitation of Liability">
        <p>
          To the extent permitted by applicable law, Fyzer is not liable for indirect or
          consequential loss arising from use of, or inability to use, the platform. Nothing in
          these Terms limits any liability that cannot be limited by law.
        </p>
      </LegalSection>

      <LegalSection id="termination" number={16} heading="Suspension and Termination">
        <p>
          Access to the platform may be suspended or terminated where these Terms are breached,
          where security or patient safety is at risk, or where required by law.
        </p>
      </LegalSection>

      <LegalSection id="changes" number={17} heading="Changes to the Terms">
        <p>
          Fyzer may update these Terms as its services, technologies or legal requirements change.
          Continued use of the platform after an update means you accept the updated Terms.
        </p>
      </LegalSection>

      <LegalSection id="applicable-law" number={18} heading="Applicable Law">
        <p>
          These Terms are governed by the laws applicable to the jurisdiction in which Fyzer
          operates the platform.
        </p>
      </LegalSection>

      <LegalSection id="contact" number={19} heading="Contact">
        <p>
          For questions regarding these Terms, contact{" "}
          <a href="mailto:admin@fyzer.com">admin@fyzer.com</a>.
        </p>
      </LegalSection>
    </LegalLayout>
  );
}
